# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='productname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
