# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171202_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 20, 43, 36, 404291)),
        ),
    ]
