# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 06:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171210_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif_for_seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=100)),
                ('notif', models.CharField(max_length=250)),
                ('seller', models.CharField(default='a', max_length=300)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notif_for_win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=100)),
                ('notif', models.CharField(max_length=250)),
                ('sold_to', models.CharField(default='a', max_length=300)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='bid_end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 6, 15, 51, 528908)),
        ),
    ]
